const TOKEN =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInRlYW1JZCI6IjUtOSIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzIxMTE4MjcyLCJleHAiOjE3MjExMjAwNzIsImlzcyI6InNwLWVwaWdyYW0ifQ.bVG8xRa-q-DWn1hKFr3g6-0XekajZqXpYMzad3EuznA';

export default TOKEN;
